import {Inter} from "next/font/google";

import Layout from "@/components/layout/Layout";

import type {Metadata} from "next";
import type {ReactNode} from 'react'

import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Next App Template",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>

export default function RootLayout(
  {
    children,
  }: RootLayoutProps) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Layout>
      {children}
    </Layout>
    </body>
    </html>
  );
}
